### PR TITLE
Attempt at fixing I2CMaster with I2CSlave

### PR DESCRIPTION
**Pull request by seijikun**
With these changes, I2CSlave and I2CMaster work together.
In this state, transmissions seem stable with frequencies of up to 390000.

### CODE REVIEW

**Comment by seijikun** [comment]
Hm... That was probably not very clever. Now the address fixes are mixed in here :(

**Comment by DavidZemon** [comment]
That's very interesting. A simple enough change.

On top of the address fixes getting mixed in, there's also whitespace fixes. Can you switch the tabs to 4-space indentations?

Also, you mention 390k as the fastest stable speed you've achieved. I know you were aiming for 400k. Do you know whether the bottleneck is master, slave or both?

**Comment by seijikun** [comment]
I think it's both.
When setting the master to 400000, it does not seem to actually be 400000. When I am using a bigger microcontroller of NXP/Phillips as master (who has I2C in hardware), the original version of the slave stops working at a frequency of around 200000. But there is a chance I did not correctly set up the NXP.

**Comment by DavidZemon** [comment]
Because of the mixed up commits, I "merged" this by cherry picking the commits and then committing them.
I also found a problem that I introduced in the `read_to_end()` function and fixed it.

**Pull request closed without merging**
