### PR TITLE
[#102] Fix regression and add user-pointer

### PR DESCRIPTION
**Pull request by seijikun**
This version works with the NXP-Controller at frequencies of about 440kHz. (Well, at least if you do the electronics correctly... :unamused:)

I furthermore added an old-school user-pointer that can be set to one value per slave, and is then passed to all the slave's callbacks. Or do you have a better solution for this usecase?
I thought about using `std::function<..>` instead, but I couldn't get it to compile. This would've allowed to use `std::bind` - which probably isn't even supported with the current compiler (didn't check).

### CODE REVIEW

**Comment by DavidZemon** [comment]
I like the user-pointer idea. I would change that to a template though, rather than `void *`. Then the demo app doesn't have to use that global `Queue` object.

That's VERY exciting that it works all the way up to 440 kHz.

I'll take a closer look at the changes when I get home to my board and a real IDE. I may end up doing a manual merge again rather than using GitHub's interface for this one.

**Comment by seijikun** [comment]
I also thought about the template idea. But it would have to be a class template, so that the member-variable can also have the correct type, right?

**Comment by DavidZemon** [comment]
Yes. And I'm okay with that.

**Comment by seijikun** [comment]
I implemented the template. I hope it works (I have no compiler to test :grin:).
I tried making it mergeable by fixing the whitespace changes... Nice how different diff tools work differently with spaces :angry:.

**Comment by DavidZemon** [comment]
Beautiful! I really like it :D. Thank you so much for working with me on this!

**Comment by DavidZemon** [comment]
Okay, I fixed the compilation errors and _finally_ ran some successful tests where I was able to have the slave echo some data from the master. YAY! Does this code, in its current state, still work for your use case?

**Comment by seijikun** [comment]
Yes, works like a charm! But you are missing as the file's author. :grinning:

**Pull request merged**
