### PR TITLE
Add initial version of timeout-reading

### PR DESCRIPTION
**Pull request by seijikun**
Added an initial version of reading with a timeout functionality. (only one byte for now)
This is done by polling for a start-bit instead of using the hardware-functionality (`waitpne`). For a nice and fast way of io-polling with a timeout, I used Phil's approach from [here](http://forums.parallax.com/discussion/comment/774604#Comment_774604)

### CODE REVIEW

**Comment by seijikun** [comment]
Is there a reason why the return-type of `receive()` is a `uint32_t`?
If there is (at least now) more than one error-code, maybe changing it to a signed integer will bring the advantage, that the check:    `result >= 0` is enough to check for success, rather than `result != -1 && result != -2`, or `result > 255` (which I find weird).

**Comment by DavidZemon** [comment]
There is a reason: I don't like returning signed types for data whose type is unknown to me. However, I agree this is a problem. Let's change the signature of `receive()` to `ErrorCode receive (uint32_t &rxVal) const` and then we can return a proper error code in the case of a parity error rather than -1. To keep API compatibility, a new method can be added with the old signature, similar to `FileReader::get_char()` in `PropWare/filesystem/filereader.h`.

**Comment by seijikun** [comment]
What exactly do you mean with the parameter `uint32_t &rxVal`? What is it?
EDIT: Nevermind... I just noticed it.

**Comment by DavidZemon** [comment]
Looking good. Just fyi, this request will require a level of concentration and time that I can't give PropWare for another 36 or 48 hours.

**Comment by seijikun** [comment]
No problem, I will start developing with my local version then.

**Comment by seijikun** [comment]
I changed `ErrorCode receive(uint32_t&)` to `ErrorCode receive(uint8_t&)` because that adds the possibility to directly pass the field of a `char[]` / `uint8_t[]` into it. (I used this functionality in `receive_array(timeout)`). Please correct me if it's possible to do this with `uint32_t&`, [but I wasn't able to get it to work](http://ideone.com/nu1XYc).
EDIT: I just noticed: This is a mistake, because the dataWidth can be greater than 8, right?

**Comment by seijikun** [comment]
I reverted the previously mentioned change and adapted the `receive_array(timeout)` method instead.
This is the version I'm currently using. Works amazingly well.

**Comment by DavidZemon** [comment]
Thank you for your work on this! I'm finally back to doing a bit of work on PropWare and have finished merging this in. I cleaned up the whitespace and found a couple places (both in your code and my own) where we should have been using PropWare's `check_errors(x)` macro, so I made those updates. I also added documentation to a number of methods that were missing it.

**Pull request merged**
